import { motion } from 'framer-motion'
import { ArrowRight, GitBranch, ShieldCheck, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

export default function Landing() {
  const navigate = useNavigate()
  return <div className="min-h-screen overflow-hidden bg-ink text-slate-200 grid-bg">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/15 text-primary">✈</div><b>TravelPilot</b></div><button onClick={()=>navigate('/plan')} className="rounded-xl border border-[rgb(var(--c-overlay)/10%)] px-4 py-2 text-sm hover:bg-[rgb(var(--c-overlay)/5%)]">Open app</button></header>
    <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-24">
      <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary"><Sparkles size={14}/> AI trip intelligence</div><h1 className="max-w-3xl text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Your trip is more than a list of bookings.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">TravelPilot understands how flights, transfers, activities and stays depend on each other — so when something breaks, you can see the impact and recover quickly.</p><button onClick={()=>navigate('/plan')} className="mt-9 inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3.5 font-semibold shadow-xl shadow-primary/20 hover:brightness-110">Plan my trip <ArrowRight size={18}/></button><p className="mt-5 text-sm text-slate-500">“Tools handle bookings, not itineraries.”</p></div>
      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="glass rounded-3xl p-6 shadow-2xl shadow-black/30"><div className="mb-6 flex items-center justify-between"><div><div className="text-xs uppercase tracking-widest text-slate-500">Live trip graph</div><div className="mt-1 text-lg font-semibold">Ladakh • 6 days</div></div><span className="rounded-full bg-success/10 px-3 py-1 text-xs text-success">● Healthy</span></div><div className="space-y-4"><Node title="Delhi → Leh" icon="✈"/><div className="ml-7 h-5 border-l border-dashed border-primary/30"/><Node title="Airport Transfer" icon="🚕"/><div className="ml-7 h-5 border-l border-dashed border-primary/30"/><Node title="Pangong Activity" icon="🏔"/><div className="ml-7 h-5 border-l border-dashed border-primary/30"/><Node title="Hotel Check-in" icon="🏨"/></div><div className="mt-7 grid grid-cols-3 gap-3"><Metric label="Nodes" value="18"/><Metric label="Dependencies" value="14"/><Metric label="Health" value="94%"/></div></motion.div>
    </section>
    <section className="mx-auto grid max-w-7xl gap-4 px-6 pb-24 md:grid-cols-3"><Feature icon={GitBranch} title="Understand" text="Model the itinerary as a dependency graph."/><Feature icon={ShieldCheck} title="Detect" text="Trace disruption impact through the trip."/><Feature icon={Sparkles} title="Recover" text="Prepare ranked recovery options with reasoning."/></section>
  </div>
}
function Node({icon,title}){return <div className="flex items-center gap-4 rounded-2xl border border-[rgb(var(--c-overlay)/8%)] bg-[rgb(var(--c-overlay)/4%)] p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[rgb(var(--c-overlay)/6%)] text-lg">{icon}</div><div className="text-sm font-semibold">{title}</div><div className="ml-auto text-xs text-success">OK</div></div>}
function Metric({label,value}){return <div className="rounded-2xl bg-[rgb(var(--c-overlay)/4%)] p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}
function Feature({icon:Icon,title,text}){return <div className="glass rounded-2xl p-6"><Icon className="text-primary" size={22}/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>}
